/*
 * subtitle_tts.js — part of Audio Transcription
 * Copyright (C) 2026 Antonio Ruiz
 *
 * This file is part of Audio Transcription.
 *
 * Audio Transcription is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Audio Transcription is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Audio Transcription. If not, see <https://www.gnu.org/licenses/>.
 */

;(function cleanupPrevious() {
  if (typeof window.__stts_onMsg === 'function')
    try { chrome.runtime.onMessage.removeListener(window.__stts_onMsg); } catch(e){}
  if (typeof window.__stts_onStorage === 'function')
    try { chrome.storage.onChanged.removeListener(window.__stts_onStorage); } catch(e){}
  if (window.__subtitleTtsApi?._cleanup)
    try { window.__subtitleTtsApi._cleanup(); } catch(e){}
  window.__stts_onMsg = window.__stts_onStorage = window.__subtitleTtsApi = null;
})();

window.__subtitleTtsApi = (function () {

  const MIN_WORDS_PUNCT  = 8;    // commit early if sentence ends with ≥N words
  const HARD_COMMIT      = 35;   // force commit at this word count to allow longer sentences
  const MAX_AGE          = 30000;
  const MAX_Q            = 4;
  const MAX_COMMITTED    = 500;  // sliding window of committed words for dedup

  const SPACELESS_RE = /[\u3040-\u9FFF\uF900-\uFAFF\u0E00-\u0EFF\u0F00-\u0FFF\u1000-\u109F\u1780-\u17FF]/;
  function isSpacelessScript(text) {
    return SPACELESS_RE.test(text);
  }
  function splitWords(text) {
    const t = String(text || '');
    if (isSpacelessScript(t)) {
      return t.replace(/\s+/g, '').split('');
    }
    return t.split(' ').filter(Boolean);
  }
  function joinWords(words) {
    if (!words || !words.length) return '';
    const first = words[0];
    if (SPACELESS_RE.test(first)) {
      return words.join('');
    }
    return words.join(' ');
  }

  let videoEl = null, activeTrack = null, obs = null, activeSel = null;
  let isSpeaking = false, isTtsSpeaking = false;
  let cueQueue = [], recentTrans = [];
  let ttsId = null, stopped = false;
  // true = TextTrack (creator-uploaded, full cues), false = DOM observer (autogenerated, word-by-word)
  let isTextTrackMode = false;

  // Accumulation state
  let pendingWords   = [];
  let committedWords = [];
  let lastSeenText   = '';
  let debTimer       = null;
  let isProgressiveMode = false;

  let isSeeking = false;
  let seekCooldownTimer = null;

  function onSeeked() {
    isSeeking = true;
    cueQueue = [];
    isSpeaking = false;
    isTtsSpeaking = false;
    pendingWords = [];
    committedWords = [];
    lastSeenText = '';
    clearTimeout(debTimer);
    clearTimeout(ttsId);

    try { 
      chrome.runtime.sendMessage({ action: 'stopTts', isSeek: true }, () => void chrome.runtime.lastError); 
    } catch(e){}

    clearTimeout(seekCooldownTimer);
    seekCooldownTimer = setTimeout(() => { isSeeking = false; }, 400);
  }

  let cfg = {
    playbackControl: 'pause', slowdownRate: 0.8,
    enableGeminiTranslation: false, enableTts: false,
    targetLanguage: 'en', ttsSpeed: 1.0, trackLang: '', sttsSelectedLanguage: '',
    hideNativeSubtitles: true, videoVolume: 1.0
  };

  const originalVideoVolumes = new Map();
  // We only skip labels like [music] or purely auto-generated tags. We don't skip short 1-word valid subtitles like "Yes."
  const SKIP = /auto.?generat|automatically|inaccurat|turn off subtitle|keyboard shortcut|^\[[a-z\s]+\]$/i;

  // Utilities
  function norm(t) { return String(t || '').replace(/\s+/g, ' ').trim(); }

  function cleanSubtitle(t) {
    return norm(
      String(t || '')
        .replace(/<[^>]+>/g, '')    
        .replace(/>+/g, '')         
        .replace(/^\s*-\s+/gm, '')  
        .replace(/[\u200B-\u200F\uFEFF\u202A-\u202E\u2066-\u2069]/g, '')
        .replace(/\n/g, ' ')
        .replace(/([.!?¿¡,;:\u2026\u3002\uFF01\uFF1F\u061F\u0964\u0965])([^\s\d"'\])}»\u201D\u2019])/g, '$1 $2')
    );
  }

  function skip(t) { return !t || SKIP.test(t); }

  function sentenceEnds(words) {
    return /[.!?¿¡,;:\u2026\u3002\uFF01\uFF1F\u061F\u0964\u0965]["'\])}»\u201D\u2019]*$/.test(words[words.length - 1] || '');
  }

  // Normalize a word for comparison: lowercase + strip trailing punctuation.
  function nw(w) { return String(w || '').toLowerCase().replace(/[.,!?;:'"…']+$/, ''); }

  // Find how many words at the END of history match the START of incoming.
  // Handles both normal growth (new words appended) and sliding-window (old words
  // dropped from start). Also handles ASR shrinkage via the loose-overlap pass.
  function committedPrefixLength(committed, incoming, bypassStaticCheck) {
    const normCom = committed.map(nw);
    const normInc = incoming.map(nw);

    // 1. Strict overlap: End of history matches Start of incoming.
    // We do NOT limit to 50 words, allowing perfect alignment for massive static windows.
    const maxOverlap = Math.min(normCom.length, normInc.length);
    for (let size = maxOverlap; size >= 1; size--) {
      let match = true;
      for (let i = 0; i < size; i++) {
        if (normCom[normCom.length - size + i] !== normInc[i]) { match = false; break; }
      }
      if (match) {
        // Prevent false-positive 1-2 word overlaps between independent sentences in static streams
        const isStaticStream = !bypassStaticCheck && (isTextTrackMode || !isProgressiveMode);
        if (isStaticStream && size < 3 && size < normInc.length) {
          continue;
        }
        return size;
      }
    }

    // 2. Safe Loose overlap: Find the largest suffix of history inside incoming.
    // This is a fallback in case MAX_COMMITTED truncated the history, or YouTube
    // randomly inserted words into the past. 
    // To prevent falsely matching repeated short phrases (like "around the area"),
    // we require the overlap to be large (>= 8 words) OR equal to the entire history.
    for (let size = maxOverlap; size >= 1; size--) {
      const suffix = normCom.slice(normCom.length - size);
      for (let i = 0; i <= normInc.length - size; i++) {
        let match = true;
        for (let k = 0; k < size; k++) {
          if (suffix[k] !== normInc[i + k]) { match = false; break; }
        }
        if (match && (size >= 8 || size === normCom.length)) {
          return i + size;
        }
      }
    }

    return 0;
  }


  function mergeCues(pending, incoming) {
    if (!pending.length) return incoming;
    if (!incoming.length) return pending;
    
    const normP = pending.map(nw);
    const normI = incoming.map(nw);

    if (incoming.length <= pending.length) {
      let isPrefix = true;
      for (let i = 0; i < incoming.length; i++) {
        if (normI[i] !== normP[i]) { isPrefix = false; break; }
      }
      if (isPrefix) return pending.slice(0, incoming.length);
    }

    const maxOverlap = Math.min(normP.length, normI.length);
    for (let size = maxOverlap; size >= 1; size--) {
      let match = true;
      for (let i = 0; i < size; i++) {
        if (normP[normP.length - size + i] !== normI[i]) {
          if (size >= 2 && i === size - 1) continue;
          if (size === 1 && i === 0) {
            const wp = normP[normP.length - 1];
            const wi = normI[0];
            if (wp.startsWith(wi) || wi.startsWith(wp)) continue;
          }
          match = false; break;
        }
      }
      if (match) return [...pending.slice(0, pending.length - size), ...incoming];
    }
    return [...pending, ...incoming];
  }


  // DOM / Track helpers
  function findVideo() {
    const all = Array.from(document.querySelectorAll('video'));
    return all.reduce((b, v) => (!b || v.offsetWidth * v.offsetHeight > b.offsetWidth * b.offsetHeight) ? v : b, null);
  }

  function findTrack(v) {
    if (!v) return null;
    const ts = Array.from(v.textTracks);
    if (!ts.length) return null;
    return ts.find(t => t.mode === 'showing')
        || ts.find(t => t.mode === 'hidden')
        || (() => { const p = ts.find(t => t.kind === 'subtitles' || t.kind === 'captions') || ts[0]; p.mode = 'hidden'; return p; })();
  }

  const DOM_SELS = [
    { c: '.ytp-caption-window-container',              t: '.ytp-caption-segment' },
    { c: '.player-captions-container__caption-window', t: '.player-captions-container__caption-line' },
    { c: '.vjs-text-track-display',                   t: '.vjs-text-track-cue' },
    { c: '#captions-overlay',                         t: '#captions-overlay span' },
    { c: '.player-timedtext',                         t: '.player-timedtext-text-container' },
  ];

  function getDomText() {
    if (!activeSel) return '';
    const ss = document.querySelectorAll(activeSel.t);
    if (ss.length) return norm(Array.from(ss).map(s => s.textContent).join(' '));
    const cc = document.querySelector(activeSel.c);
    return cc ? norm(cc.textContent) : '';
  }

  function findDom() {
    for (const s of DOM_SELS) if (document.querySelector(s.c)) return s;
    return null;
  }

  // Accumulation
  function accumulateText(rawText) {
    if (stopped || isSeeking) return;

    const clean = cleanSubtitle(rawText || '');

    if (!clean) {
      if (lastSeenText !== '') {
        lastSeenText = '';
        if (pendingWords.length > 0) {
          clearTimeout(debTimer);
          debTimer = setTimeout(flushPending, 1200);
        }
      }
      return;
    }

    const prevText = lastSeenText;
    if (clean === lastSeenText) return;
    lastSeenText = clean;

    clearTimeout(debTimer);

    const allWords = splitWords(clean);

    if (!isProgressiveMode && prevText) {
      const lastWords = splitWords(prevText);
      const overlap = committedPrefixLength(lastWords, allWords, true);
      const isSubset = lastWords.every((w, i) => nw(w) === nw(allWords[i])) ||
                       allWords.every((w, i) => nw(w) === nw(lastWords[i]));
      if (overlap >= 3 || isSubset) {
        isProgressiveMode = true;
      }
    }

    const skipCommitted = committedPrefixLength(committedWords, allWords, false);
    const fresh = allWords.slice(skipCommitted);

    if (!fresh.length) {
      if (pendingWords.length) evaluateCommit();
      return;
    }

    if (isTextTrackMode) {
      pendingWords = [...pendingWords, ...fresh];
    } else {
      pendingWords = mergeCues(pendingWords, fresh);
    }

    evaluateCommit();
  }

  function evaluateCommit() {
    const wc = pendingWords.length;
    if (!wc) return;

    // --- Hard commit: prevent unbounded accumulation ---
    if (wc >= HARD_COMMIT) {
      const splitPoint = Math.max(1, wc - 1);
      const sentence   = pendingWords.slice(0, splitPoint);
      const remainder  = pendingWords.slice(splitPoint);
      const text = joinWords(sentence);
      committedWords = [...committedWords, ...sentence];
      if (committedWords.length > MAX_COMMITTED) committedWords = committedWords.slice(-MAX_COMMITTED);
      commitText(text);
      pendingWords = remainder;
      return;
    }

    // --- Punctuation regexes (multilingual, nothing hardcoded) ---
    const RE_STRONG = /[.!?\u2026\u3002\uFF01\uFF1F\u061F\u0964\u0965]["'\])}»\u201D\u2019]*$/;
    const RE_MEDIUM = /[;:\u061B\uFF1B\uFF1A]["'\])}»\u201D\u2019]*$/;
    const RE_WEAK   = /[,\-\u060C\u3001]["'\])}»\u201D\u2019]*$/;
    const RE_OPEN_Q = /^[¿¡]/;
    // Conjunctions that likely continue the same sentence after a period
    // (kept minimal and language-agnostic: only unambiguous English coordinators)
    const RE_CONTINUATION = /^(and|but|or|so|yet|for|nor)$/i;

    const isStaticMode = isTextTrackMode ||
      pendingWords.some(w => /[.,!?;:\u3002\uFF01\uFF1F\u061F\u0964\u0965\u060C\u061B\u3001\uFF1B\uFF1A]/.test(w));

    // --- Scan the full array for the first strong internal split point ---
    // This fixes the core bug: two sentences inside one pending buffer were
    // committed as a single utterance because only the last token was checked.
    let internalSplitIdx = -1;
    for (let i = MIN_WORDS_PUNCT - 1; i < wc - 1; i++) {
      if (RE_STRONG.test(pendingWords[i])) {
        const nextWord = pendingWords[i + 1] || '';
        // Skip if next word is a lowercase conjunction — likely a mid-sentence period
        // (e.g. abbreviations, "etc. and", "U.S. and")
        if (RE_CONTINUATION.test(nextWord) && /^[a-z]/.test(nextWord)) continue;
        internalSplitIdx = i;
        break;
      }
    }

    if (internalSplitIdx !== -1) {
      const sentence = pendingWords.slice(0, internalSplitIdx + 1);
      pendingWords   = pendingWords.slice(internalSplitIdx + 1);
      const text = joinWords(sentence);
      committedWords = [...committedWords, ...sentence];
      if (committedWords.length > MAX_COMMITTED) committedWords = committedWords.slice(-MAX_COMMITTED);
      commitText(text);
      // Re-evaluate the remainder immediately — there may be another split point
      if (pendingWords.length >= MIN_WORDS_PUNCT) evaluateCommit();
      return;
    }

    // --- No internal split found: fall back to last-token detection ---
    const lastWord     = pendingWords[wc - 1] || '';
    const hasStrong    = RE_STRONG.test(lastWord);
    const hasMedium    = RE_MEDIUM.test(lastWord);
    const hasWeak      = RE_WEAK.test(lastWord);

    if (isStaticMode) {
      if (hasStrong && wc >= MIN_WORDS_PUNCT) {
        flushPending();
      } else if (hasStrong && wc < MIN_WORDS_PUNCT) {
        clearTimeout(debTimer);
        debTimer = setTimeout(flushPending, 800);
      } else if (hasMedium && wc >= 12) {
        flushPending();
      } else if (hasWeak && wc >= 18) {
        flushPending();
      } else if (wc >= 22) {
        // Scan backwards for the best mid-array split point
        let splitIdx = -1;
        for (let i = wc - 2; i >= 10; i--) {
          if (RE_MEDIUM.test(pendingWords[i]) || RE_OPEN_Q.test(pendingWords[i + 1] || '')) {
            splitIdx = i;
            break;
          }
        }
        if (splitIdx === -1) {
          for (let i = wc - 2; i >= 14; i--) {
            if (RE_WEAK.test(pendingWords[i])) {
              splitIdx = i;
              break;
            }
          }
        }
        if (splitIdx !== -1) {
          const sentence = pendingWords.slice(0, splitIdx + 1);
          pendingWords   = pendingWords.slice(splitIdx + 1);
          const text = joinWords(sentence);
          committedWords = [...committedWords, ...sentence];
          if (committedWords.length > MAX_COMMITTED) committedWords = committedWords.slice(-MAX_COMMITTED);
          commitText(text);
        } else {
          clearTimeout(debTimer);
        }
      } else {
        clearTimeout(debTimer);
      }
    } else {
      // Progressive / DOM observer mode: use timers, don't flush synchronously
      if (hasStrong && wc >= MIN_WORDS_PUNCT) {
        clearTimeout(debTimer);
        debTimer = setTimeout(flushPending, 400);
      } else if (hasMedium && wc >= MIN_WORDS_PUNCT) {
        clearTimeout(debTimer);
        debTimer = setTimeout(flushPending, 1000);
      } else if (hasWeak && wc >= 15) {
        clearTimeout(debTimer);
        debTimer = setTimeout(flushPending, 1500);
      } else {
        clearTimeout(debTimer);
        debTimer = setTimeout(flushPending, 4000);
      }
    }
  }

  function flushPending() {
    clearTimeout(debTimer);
    if (!pendingWords.length) return;
    const text = joinWords(pendingWords);
    pendingWords = [];
    lastSeenText = '';

    committedWords = [...committedWords, ...splitWords(text)];
    if (committedWords.length > MAX_COMMITTED) committedWords = committedWords.slice(-MAX_COMMITTED);

    commitText(text);
  }

  // Video sync
  function syncVideoSpeed() {
    if (!videoEl || cfg.playbackControl === 'none' || !cfg.enableTts) return;
    
    if (cfg.playbackControl === 'pause') {
      if (cueQueue.length >= 2 && isSpeaking) {
        applyCtrl();
      } else if (cueQueue.length < 2) {
        restoreCtrl();
      }
    } else if (cfg.playbackControl === 'slowdown') {
      const baseR = Math.max(0.1, cfg.slowdownRate);
      const qDepth = Math.max(0, cueQueue.length - 1);
      const dynamicR = Math.max(0.1, baseR - (qDepth * 0.15));
      if (cueQueue.length > 0 && isSpeaking) {
        applyCtrl(dynamicR);
      } else {
        restoreCtrl();
      }
    }
  }

  // Event handlers
  function onMutation() { if (!stopped) accumulateText(getDomText()); }

  function onCueChange() {
      if (stopped || !activeTrack) return;
      const cues = activeTrack.activeCues;
      if (!cues || !cues.length) { accumulateText(''); return; }
      isTextTrackMode = true;
      const newText = Array.from(cues).map(c => c.text || '').join(' ');
      accumulateText(newText);
  }

  function startObs(sel) {
    activeSel = sel;
    const c = document.querySelector(sel.c);
    if (!c) return false;
    if (obs) obs.disconnect();
    // DOM observer = autogenerated (word-by-word)
    isTextTrackMode = false;
    obs = new MutationObserver(onMutation);
    obs.observe(c, { childList: true, subtree: true, characterData: true });
    console.log('[SubtitleTTS] DOM obs:', sel.c);
    return true;
  }

  // Display
  function showContent(orig, disp, statusText, currentSrcLang) {
    try {
      chrome.runtime.sendMessage(
        { type: 'subtitle_display', data: { original: orig, translated: disp, statusText: statusText, trackLang: currentSrcLang } },
        () => void chrome.runtime.lastError
      );
    } catch(e) {}
  }

  // Video control
  function applyCtrl(rateOverride) {
    if (!videoEl) return;
    try {
      if (cfg.playbackControl === 'pause') {
        document.querySelectorAll('video').forEach(v => {
          if (v.offsetWidth > 0) { v.dataset.sttsPaused = '1'; v.pause(); }
        });
      } else if (cfg.playbackControl === 'slowdown' && rateOverride !== undefined) {
        document.querySelectorAll('video').forEach(v => {
          if (v.offsetWidth > 0) {
            if (!v.dataset.stts_rate) v.dataset.stts_rate = v.playbackRate || 1;
            v.playbackRate = rateOverride;
          }
        });
      }
    } catch(e) {}
  }

  function restoreCtrl() {
    try {
      document.querySelectorAll('video').forEach(v => {
        if (v.offsetWidth > 0) {
          if (v.dataset.stts_rate) { v.playbackRate = parseFloat(v.dataset.stts_rate) || 1; delete v.dataset.stts_rate; }
          if (v.dataset.sttsPaused) { delete v.dataset.sttsPaused; v.play().catch(() => {}); }
        }
      });
    } catch(e) {}
  }

  function applyVideoVolume(force = false) {
    try {
      document.querySelectorAll('video').forEach(v => {
        if (v.offsetWidth > 0) {
          if (!originalVideoVolumes.has(v)) {
            originalVideoVolumes.set(v, v.volume);
          }
          v.volume = Math.max(0, Math.min(1, cfg.videoVolume));
        }
      });
    } catch(e) {}
  }
  function restoreVideoVolume() {
    try {
      document.querySelectorAll('video').forEach(v => {
        if (originalVideoVolumes.has(v)) { v.volume = originalVideoVolumes.get(v); originalVideoVolumes.delete(v); }
      });
    } catch(e) {}
    originalVideoVolumes.clear();
  }

  // TTS queue
  function speak(text, lang) {
    chrome.runtime.sendMessage(
      { action: 'subtitleSpeak', text: norm(text), lang: lang || '', ttsSpeed: cfg.ttsSpeed },
      () => void chrome.runtime.lastError
    );
  }

  function commitText(text) {
    const t = norm(text);
    if (skip(t)) return;

    cueQueue.push({ text: t, ts: Date.now() });
    console.log('[SubtitleTTS] commit:', t.slice(0, 80));
    syncVideoSpeed();
    if (!isSpeaking) processQueue();
  }

  function onDone() {
    clearTimeout(ttsId);
    ttsId = null; isSpeaking = false; isTtsSpeaking = false;
    syncVideoSpeed();
    if (!stopped) processQueue();
  }

  async function processQueue() {
    if (stopped || isSpeaking || !cueQueue.length) return;
    const now = Date.now();
    while (cueQueue.length && (now - cueQueue[0].ts) > MAX_AGE) cueQueue.shift();
    while (cueQueue.length > MAX_Q) cueQueue.shift();
    const item = cueQueue.shift();
    if (!item) return;

    isSpeaking = true;
    syncVideoSpeed();

    let currentSrcLang = cfg.sttsSelectedLanguage || cfg.trackLang;

    // Auto-detect language natively if missing and we have enough text
    if (!currentSrcLang && item.text.trim().length >= 3) {
      try {
        const res = await new Promise(resolve => {
           chrome.runtime.sendMessage({ action: 'detectTextLanguage', text: item.text }, resolve);
        });
        if (res && res.language) {
          currentSrcLang = res.language;
          cfg.trackLang = res.language;
          showContent(null, null, undefined, currentSrcLang); 
        }
      } catch(e) {}
    }

    const needsTrans = cfg.enableGeminiTranslation;

    if (needsTrans) {
      showContent(item.text, '', 'Translating...', currentSrcLang);
      const tail = recentTrans.slice(-2).join(' ');
      chrome.runtime.sendMessage({ action: 'processTranslation', text: item.text, shownTail: tail, skipTts: true, sourceLang: currentSrcLang }, (r) => {
        void chrome.runtime.lastError;
        if (stopped) { isSpeaking = false; isTtsSpeaking = false; restoreCtrl(); return; }
        
        const rawData = norm(r?.data || '');
        const cleanTr = rawData.replace(/^\u207A\s*/, '');
        const st = rawData || item.text;
        const lang = cleanTr ? cfg.targetLanguage : (currentSrcLang || '');
        const geminiError = r?.geminiError || '';
        
        let statusMsg = cleanTr ? 'Translation Active' : '';
        if (geminiError) statusMsg = `GT fallback — Gemini: ${geminiError}`;
        else if (!r?.success) statusMsg = `Translation Error: ${r?.error || 'Unknown'}`;

        if (cleanTr) { recentTrans.push(cleanTr); if (recentTrans.length > 10) recentTrans.shift(); }
        
        showContent(item.text, st, statusMsg, currentSrcLang);
        
        if (cfg.enableTts) { isTtsSpeaking = true; ttsId = setTimeout(onDone, 20000); speak(cleanTr || item.text, lang); }
        else setTimeout(onDone, 50);
      });
    } else {
      showContent(item.text, '', '', currentSrcLang);
      if (cfg.enableTts) { isTtsSpeaking = true; ttsId = setTimeout(onDone, 20000); speak(item.text, currentSrcLang || ''); }
      else setTimeout(onDone, 50);
    }
  }

  // Init / Stop
  function resetState() {
    clearTimeout(debTimer); clearTimeout(ttsId);
    isSpeaking = false; isTtsSpeaking = false;
    pendingWords = []; committedWords = []; lastSeenText = '';
    cueQueue = []; recentTrans = [];
    debTimer = null; ttsId = null;
    isTextTrackMode = false;
    isProgressiveMode = false;
  }

  async function init(settings) {
    resetState();
    stopped = false;
    if (settings) cfg = { ...cfg, ...settings };
    videoEl = findVideo();
    if (!videoEl) return { success: false, error: 'no_video' };
    applyVideoVolume(true);

    try {
      const ccBtn = document.querySelector('.ytp-subtitles-button');
      if (ccBtn && ccBtn.getAttribute('aria-pressed') === 'false') ccBtn.click();
      if (cfg.hideNativeSubtitles !== false && !document.getElementById('stts-hide-cc')) {
        const s = document.createElement('style');
        s.id = 'stts-hide-cc';
        s.textContent = '.ytp-caption-window-container, .caption-window { opacity: 0.01 !important; pointer-events: none !important; }';
        document.head.appendChild(s);
      }
    } catch(e) {}

    const bgSearch = setInterval(() => {
      if (stopped) { clearInterval(bgSearch); return; }
      
      const currentVideo = findVideo();
      if (currentVideo !== videoEl) {
        if (obs) { obs.disconnect(); obs = null; activeSel = null; }
        if (activeTrack) { activeTrack.removeEventListener('cuechange', onCueChange); activeTrack = null; }
        if (videoEl) { videoEl.removeEventListener('seeked', onSeeked); }
        videoEl = currentVideo;
        if (videoEl) { videoEl.addEventListener('seeked', onSeeked); }
        applyVideoVolume(true); 
      } else {
        applyVideoVolume(false); 
      }

      if (!videoEl) return;

      if (!activeTrack && !obs) {
        const t = findTrack(videoEl);
        if (t) {
          activeTrack = t;
          cfg.trackLang = activeTrack.language || '';
          if (activeTrack.mode === 'disabled') activeTrack.mode = 'hidden';
          activeTrack.addEventListener('cuechange', onCueChange);
          console.log('[SubtitleTTS] TextTrack lang:', cfg.trackLang);
        } else {
          const sel = findDom();
          if (sel && startObs(sel)) { console.log('[SubtitleTTS] DOM obs attached.'); }
        }
      } else if (activeTrack && activeTrack.mode === 'disabled') {
         activeTrack.removeEventListener('cuechange', onCueChange);
         activeTrack = null;
      } else if (obs && activeSel && !document.querySelector(activeSel.c)) {
         obs.disconnect(); obs = null; activeSel = null;
      }
    }, 1000);

    return { success: true };
  }

  function _cleanup() {
    stopped = true;
    if (obs) { obs.disconnect(); obs = null; }
    if (activeTrack) { activeTrack.removeEventListener('cuechange', onCueChange); activeTrack = null; }
    if (videoEl) { videoEl.removeEventListener('seeked', onSeeked); }
    const s = document.getElementById('stts-hide-cc');
    if (s) s.remove();
    restoreCtrl(); restoreVideoVolume(); resetState(); activeSel = null;
  }

  function stop() {
    _cleanup();
    try { chrome.runtime.sendMessage({ action: 'stopTts' }, () => void chrome.runtime.lastError); } catch {}
    try { chrome.runtime.sendMessage({ type: 'STOP' },     () => void chrome.runtime.lastError); } catch {}
    console.log('[SubtitleTTS] Stopped.');
  }

  // Listeners
  function onMsg(req, sender, res) {
    if (!req?.type) return false;
    switch (req.type) {
      case 'SUBTITLE_TTS_INIT':
        init(req.settings).then(res).catch(e => res({ success: false, error: String(e) }));
        return true;
      case 'SUBTITLE_TTS_DONE': onDone(); return false;
      case 'STOP_SUBTITLE_TTS': stop(); res({ success: true }); return false;
      default: return false;
    }
  }

  function onStorageChange(changes, area) {
    if (area !== 'local') return;
    if (changes.subtitlePlaybackControl)    cfg.playbackControl         = changes.subtitlePlaybackControl.newValue    || 'pause';
    if (changes.subtitleSlowdownRate)       cfg.slowdownRate            = parseFloat(changes.subtitleSlowdownRate.newValue) || 0.8;
    if (changes.enableGeminiTranslation)    cfg.enableGeminiTranslation = !!changes.enableGeminiTranslation.newValue;
    if (changes.targetLanguage)             cfg.targetLanguage          = changes.targetLanguage.newValue || 'en';
    if (changes.sttsSelectedLanguage)       cfg.sttsSelectedLanguage    = changes.sttsSelectedLanguage.newValue || '';
    if (changes.ttsSpeed)                   cfg.ttsSpeed                = parseFloat(changes.ttsSpeed.newValue) || 1.0;
    if (changes.enableTts)                  cfg.enableTts               = !!changes.enableTts.newValue;
    if (changes.subtitleVideoVolume !== undefined) {
      cfg.videoVolume = parseFloat(changes.subtitleVideoVolume.newValue || '1.0');
      if (!stopped) applyVideoVolume(true);
    }
    if (changes.hideNativeSubtitles) {
      cfg.hideNativeSubtitles = changes.hideNativeSubtitles.newValue !== false;
      const existing = document.getElementById('stts-hide-cc');
      if (cfg.hideNativeSubtitles && !existing) {
        const s = document.createElement('style');
        s.id = 'stts-hide-cc';
        s.textContent = '.ytp-caption-window-container, .caption-window { opacity: 0.01 !important; pointer-events: none !important; }';
        document.head.appendChild(s);
      } else if (!cfg.hideNativeSubtitles && existing) { existing.remove(); }
    }
  }

  chrome.runtime.onMessage.addListener(onMsg);
  chrome.storage.onChanged.addListener(onStorageChange);
  window.__stts_onMsg     = onMsg;
  window.__stts_onStorage = onStorageChange;

  return { reinit: (s) => init(s), stop, _cleanup };
})();
